use_frameworks!

platform :ios, '9.0'

target 'LogFilePod_Example' do
  pod 'SSZipArchive', '~> 2.4.2'
  pod 'LogFilePod', :path => '../'

  target 'LogFilePod_Tests' do
    inherit! :search_paths

    
  end
end
