# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LogFilePodProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SSZipArchive', '~> 2.4.2'

  # Pods for LogFilePodProj

  target 'LogFilePodProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LogFilePodProjUITests' do
    # Pods for testing
  end

end
